### ISSUE TITLE
リソース・DB設計

### ISSUE THREAD

**Issue by reckyy** [reckyy/tsundoku#2]

**Comment by reckyy** [comment]
エレベーターピッチ
https://bootcamp.fjord.jp/products/18821

ペーパープロトタイプ
https://bootcamp.fjord.jp/products/18978

**Comment by reckyy** [comment]
# リソース設計

<h2>フロントエンド</h2>

Method | Path | Description
-- | -- | --
  | /welcome | ログイン前のTopページ
  | / | ログイン後のTopページ
  | books/:book_id/memos | 本のメモ画面
  | /search | 本の検索画面
  | /result | 本の検索結果
  | /:username | 公開ページ（そのユーザーの）
  | /delete_account | アカウント削除の確認画面
  | /error | エラー画面
  | /terms | 利用規約
  | /privacy_policy | プライバシーポリシー

<h2>バックエンド</h2>

Method | Path | Description
-- | -- | --
POST | /api/v1/users | ユーザー作成
POST | /api/v1/login | ログイン
DELETE | /api/v1/logout | ログアウト
DELETE | /api/v1/users/:user_id | ユーザー削除
POST | /api/v1/books | 本を新規登録する
GET | /api/v1/books/:book_id/memos | 本のメモ画面表示
POST | /api/v1/books/:book_id/memos | メモ内容を保存
PATCH | /api/v1/books/:book_id/memos | メモ内容を更新
DELETE | /api/v1/books/:book_id | 本の削除

- 本のメモ画面のPathが複数形なのは、そのページで各章ごとにメモを抱えているためです。
- 本の登録モーダル、削除モーダルは含めていません。




![Image](https://github.com/reckyy/Tsundoku/assets/106903482/af308dec-5d8c-4f5b-a552-aaa20e5e2dc4)


- `email`にはバリデーション(uniqueness)、NULL制約をつける。
- `password` カラムはGoogleログインのみなので設けていません。

**Comment by u1tnk** [comment]
## URL
### react
- `books/:book_id/memos` の先頭の/が無いのはミスと思います。
- `/:username` 強いこだわりが無ければ `/users/:username` など prefixは入れた方が良いですね。キーワードの予約が必要になります、後からURLを追加するときも大変です。
- `/search`、`/result` の特に後者は抽象的過ぎると思います。検索対象(ユーザなど)、結果の対象(本の登録結果など)を入れようと思ったときにぶつかりそうです。
- `/delete_account` これだと確認画面ではなく、実行するためのURLに見えます。

## rails
- `/api` は最初のエントリポイントなどとも分けるために必要なのは理解できますが `/v1` は必要でしょうか？ 名前付け的に機能拡張はあまり考えてなさそうなのに将来の大規模バージョンアップの為の prefixが必要とは思えないです。
- `DELETE /api/v1/lolgout` はログアウト状態をDELETEしそうで混乱します。 POST/DELETEで分けたいなら `/api/v1/session` とかでしょうか？認証にgemを使うならそれにも依存するでしょうし、仮のURLで良いとは思います。
- `PATCH | /api/v1/books/:book_id/memos | メモ内容を更新` は `/api/v1/books/:book_id/memos/memo_id` じゃないとメモの特定ができなさそうです。
- メモを削除するAPIが無さそうです。
- chapter関係のAPIも無さそうです
- reading_log関係のAPIも無さそうですがデータ構造的にmemoと同時を想定してます？必


## DB
- データ構造的にreading_logは memoと一対一になっているようですが、 `read_date` しか reading_log独自の情報が無いのでmemoだけで良さそうに思います。もちろん memoが編集可能のようなので、そのときは read_dateはどうするのか？という疑問があります。
    - 編集したら reading_logが増えるのであれば 一対多になりますね。
    - reading_log だけ user_idが別にあるのは何故でしょうか？ memoと違うユーザはつけないような気がします。
- memosにテキストを保存するcolumnが無いようですが、必要無いでしょうか？
- book_chaptersの chapterは intのようですが、 1章の1しょうか？そうであれば本によってはテキストのものもあると思います(序章など)
- chapterとmemoとreading_logが全て一対一ですが、仕様的にちょっと違和感を感じています。
    - 章の名前とか気にせずメモ書きたいときがありそう。
    - 章が同じで何日も読むことはありそう  
- `users.avatar`と `books.image_url` はどちらもurlが入るのでしょうか？そうであれば前者は `avatar_url` と合わせましょう。
- `books.image_url` は画像の種類が増えることは想定してなさそうですね。無さそうな気もしますが、可能性があるなら `cover_image_url` とかにしとくと無難です。
- usersとbooksは 多対多の関連もあるし一対多の関連も書いてますがおそらく多対多の方が正しそうですね。
    - 多対多ということは複数人で本を共有するという事に見えますが本が削除できて良いでしょうか？
        - もちろん誤登録ということもありますが、どう処理するかも含めて考えてみてください。

**Comment by u1tnk** [comment]
> その際、URLのクエリパラメータに章の情報を含め、それをRailsで取得して保存や更新を実行する予定です。そのため、今回はChapter専用のAPIは用意していません。

はい、それは問題無いです。メモと同時に更新するということですね。


> 想定していました。メモを保存する際に読書記録も同時に更新する設計を考えていました。もし何か問題がございましたら、教えていただきたいです😭

前回は reeading_logと一対一になっていたのでおかしいという指摘をしました。
今は一対多になっているのでそれ自体は問題無いです。
懸念しているのはメモをちょっとした編集をするときと追記したときと区別がつかなそうなので、ユーザの意図と同じ動作になるためにはどうすれば良いのか？というところです。
例えばタイプミスの編集を何回かやったら草が濃くなったらおかしいとかですね。


> memo_idと read_dateをuniqueにすることで、同じ章を何日も読んだとしてもログとして記録できるようにする

はい、これは問題無いです。ちなみにdateということは一日に一回ということでしょうか？時刻まで使うなら timeにしましょう。カラム名のrails的な慣習からすると read_at ですね。

> 考慮が足りていませんでした。ただ数字で管理したいので、本の章の登録時

これですが、本当に可能でしょうか？
例えば僕の好きな化物語シリーズだと章の名前が「まよいマイマイ」とか…まあ特定の本に考えなくても短編集なども無理がありますね。
なので、章の名前が数値というのは無理があるので名前と順番の二つを管理するとかはどうでしょう？

> これは完全に自分のエゴになりますが、章ごとにメモを管理するのは絶対条件にしたいです。

エゴというとわがままっぽいですが、やりたいことであればコンセプトとして大事にして良いと思います。やりたいことを実現するための設計です。(できないこともありますが)


> （ユーザーが本の登録時に章の数を登録するのを想定していたが、現状の設計だとユーザーが章を登録するたびに更新される。また、序章や後書きはユーザーによって含める含めないがあるため、そこでも矛盾が生じる）

はい、そうですね。運営がマスタ(ユーザが編集できないデータのことをこう呼びます)として管理するならともかく、ユーザによって分かれそうなものにユーザがメモを付けていくのは無理がありそうですね。

サービスでよほど制限しないとメモの内容の粒度がユーザによってバラバラになりそうです。
- 本の前半と後半の二回メモを取って終わり。
- 一章ずつきっちりメモを取りつつ、最後に本の全体の感想を書きたい
- どこまで読んだかのメモだけを取りたい

…とかでしょうか？もっと色々あると思います。

現状 DBにchaptersテーブルが無く、chapter_idだけがあるのはここらへんの設計が固まってないからだとは思います。
想定する複数のユーザが矛盾なくデータを入れられるように仮データを作ってみるなどして検討してみてください 💪

**Comment by reckyy** [comment]
レコードを紙に書き出し、矛盾があったDB設計についても見直しを行いました。

- `user_books` テーブルにidを追加しました。
- `books` と `memos` が一対多ではなく、 `user_books` と `memos` が一対多でしたので、そのように修正しました。
- 新たに `headings` テーブルを追加しました。章立てではない本でも見出しはあると思うので、その見出しの順番と題目を一応登録できるようにしました。

以下、ご指摘への回答になります。

> 懸念しているのはメモをちょっとした編集をするときと追記したときと区別がつかなそうなので、ユーザの意図と同じ動作になるためにはどうすれば良いのか？というところです。
例えばタイプミスの編集を何回かやったら草が濃くなったらおかしいとかですね。


保存しようとしているメモの memo_id と read_at のセットが既に存在する場合、その保存操作はスキップすることで対処しようと考えています。

> ちなみにdateということは一日に一回ということでしょうか？時刻まで使うなら timeにしましょう。カラム名のrails的な慣習からすると read_at ですね。

はい、一つの章に対するログは1日に一回と考えていました。 `read_at`に変更しました。



> これですが、本当に可能でしょうか？
例えば僕の好きな化物語シリーズだと章の名前が「まよいマイマイ」とか…まあ特定の本に考えなくても短編集なども無理がありますね。
なので、章の名前が数値というのは無理があるので名前と順番の二つを管理するとかはどうでしょう？

今回、このアプリは読書ログや読んできた本を外部にアピールすることで、読書週間の維持に貢献させたいという思いがあります。（エレベーターピッチには読んできた本をアピール、とは記載していませんでした。。）
技術書やビジネス本を対象に考えていたため、章は大体数字だと決めつけていました。
冒頭の3つ目に記載していますが、u1tnkさんの案を採用させていただいた形になりました。

> サービスでよほど制限しないとメモの内容の粒度がユーザによってバラバラになりそうです。
本の前半と後半の二回メモを取って終わり。
一章ずつきっちりメモを取りつつ、最後に本の全体の感想を書きたい
どこまで読んだかのメモだけを取りたい
…とかでしょうか？もっと色々あると思います。

そちらに関しては、自分が使いたいアプリなので、章（見出し）ごとにメモを取るしかできないようにしています。（ペーパープロトタイプの③の画面です）

**Comment by u1tnk** [comment]
> 保存しようとしているメモの memo_id と read_at のセットが既に存在する場合、その保存操作はスキップすることで対処しようと考えています。

同じ日のデータは1件と来まっているなら read_dateに戻した方が良いんじゃないかと思います。
同日のデータがあったらスキップでも良い▽ですが、DBで制約かけられた方が確実です。
これは修正必須というほどじゃないので留意ください。

> そちらに関しては、自分が使いたいアプリなので、章（見出し）ごとにメモを取るしかできないようにしています。（[ペーパープロトタイプ](https://bootcamp.fjord.jp/products/18978)の③の画面です）

「章ごとにメモを取るアプリ」というコンセプトなのであれば大丈夫です 🙆‍♀️ 
個人的には本単位で感想書くのが普通と思うので、そのあたりのコンセプトはトップページなどに分かるようにアピールしてあると良いかなと思いました 💪
